apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ include "ocp-openjdk.fullname" . }}
    {{- include "ocp-openjdk.labels" . | nindent 4 }}
  name: {{ include "ocp-openjdk.fullname" . }}
